### ISSUE TITLE
Unrecoverable panic on open file

### ISSUE THREAD

**Issue by fzerorubigd** [tealeg/xlsx#125]
I have a web application, and there is a panic/recover middleware to handle any type of un-handled panic, but here in this line : https://github.com/tealeg/xlsx/blob/b004da14c3ea7a710f0c8a4ee802af89c5952c98/lib.go#L611 there is a go rutine, and when I have a panic in read file (currently an index out of range) since its in another routine than my web request, it crash the app, and there is no way to handle this. 

Why this part is in a go routine??

**Comment by ShawnMilo** [comment]
Please provide a file that causes the panic and I'll have a look.

**Comment by fzerorubigd** [comment]
@ShawnMilo The file is not the problem here, also I can provide it https://transfer.sh/1Z7TQ/c-aghili.xlsx 
the actua problem is, you run this inside a goroutine, *unprotected*. there is *NO WAY* for me as a user for this library to prevent this panic, my web server in production, get a panic by user input and crashed, which is not acceptable.  I do many checks to prevent crash, but this one is out of my control.

**Comment by ShawnMilo** [comment]
@fzerorubigd Thank you for providing the file. In any case, if there is a panic in the library, it is a bug and should be fixed. As for disputing the architecture, I'm pinging @tealeg (the owner of this project) for his opinion.

Meanwhile, I'm going to see if I can figure out this bug. I was able to replicated it with your file.

**Comment by fzerorubigd** [comment]
think if the user input is somehow crafted file, that this library correctly refuse to load. then what? the application is getting a crash as result. 
@tealeg  I think, if any library spawn a go routine, that library is responsible for any panic in that go rutine . since there is no way for caller to prevent that panic, nor a good way to debug it, which is very bad for i.e. a web server.

**Comment by ShawnMilo** [comment]
@fzerorubigd While I agree that the library is responsible for fixing its own bugs, I don't think it's true that there should be `recover()` statements littered throughout if the library itself doesn't call `panic()`. I've tracked down the bug which, as you know, is an `index out of range` error.

So, there's a bug. It results in a panic. I think the best course of action is to fix the bug. Reading the source, the reason it's in a goroutine is because it's possible to process each sheet in parallel, so it's for better performance.

If it was not in a goroutine and you were able to `recover()` in your application, that would only mask the bug and keep the library from getting fixed.

I know exactly where the problem is and I'm just working on figuring out the correct way to solve it, which involves understanding what it's doing a bit better. It does seem that it could be due to a malformed XLSX file, because a value from the XML is part of the problem causing the index error.

**Comment by ShawnMilo** [comment]
This patch fixes the problem. I still have to figure out how to test it. @tealeg: Any recommendation on whether this is the right way to fix it?

@fzerorubigd: In the meantime, you can use this patch to fix your site.

```diff
diff --git lib.go lib.go
index 93c3305..339de33 100644
--- lib.go
+++ lib.go
@@ -471,13 +471,17 @@ func readRowsFromSheet(Worksheet *xlsxWorksheet, file *File) ([]*Row, []*Col, in
 		rows[rowIndex] = makeEmptyRow()
 	}
 
+	numRows := len(rows)
 	for rowIndex := 0; rowIndex < len(Worksheet.SheetData.Row); rowIndex++ {
 		rawrow := Worksheet.SheetData.Row[rowIndex]
 		// Some spreadsheets will omit blank rows from the
 		// stored data
 		for rawrow.R > (insertRowIndex + 1) {
 			// Put an empty Row into the array
-			rows[insertRowIndex-minRow] = makeEmptyRow()
+			index := insertRowIndex - minRow
+			if index < numRows {
+				rows[index] = makeEmptyRow()
+			}
 			insertRowIndex++
 		}
 		// range is not empty and only one range exist
```

The problem is bad input. One of the rows in sheet4.xml contains this:

```xml
<row r="1048576" 
```

The rows leading up to it are:

```xml
<row r="256"...
<row r="257"...
<row r="258"...
```

So, using `rawrow.R` as part of the loop condition is the problem, because the value for `r` can't be trusted.

**Comment by fzerorubigd** [comment]
So you say, if I get a wrong file that this library can not handle, my web server should crash (instead of simply return an error page, or even an internal server error page), many user must suffer, since a single user mistake on uploading a correct file (or worse, if a single user simply send a crafted file) this is a security bug. I love this library, its very fast, but what is the point of fast if its not safe?

**Comment by tealeg** [comment]
@ShawnMilo  and @fzerorubigd sorry it's taken me so long to get around to reading this.

@ShawnMilo I've seen issues like this before in other areas, it's just an optimisation of the file format that it allows empty parts of the sheet to be omitted - and as such your patch is correct.  To test it I would simply create the same case in a minimal set of XML input, it might require an additional test case.

Furthermore, I agree that it's a much better idea to address the root cause of the error that try and put some generic trap in place for any panic that might occur.

**Comment by fzerorubigd** [comment]
I don't care about panic in your library. I need to handle this panic in my application. the main question is still there. 
You want to find the problems in your library, its OK, but my app is not your lab.

**Comment by fzerorubigd** [comment]
How I can re-open this one? or I need to create exact same one?
