### ISSUE TITLE
Add support for XLSB

### ISSUE THREAD

**Issue by untoldone** [tealeg/xlsx#136]
Current error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb95e8]

goroutine 1 [running]:
archive/zip.(*File).findBodyOffset(0x0, 0xe87ac, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/archive/zip/reader.go:196 +0x298
archive/zip.(*File).Open(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/archive/zip/reader.go:133 +0x63
github.com/tealeg/xlsx.readWorkbookRelationsFromZipFile(0x0, 0xd, 0x0, 0x0)
	/Users/untoldone/Source/go/src/github.com/tealeg/xlsx/lib.go:747 +0x7e
github.com/tealeg/xlsx.ReadZipReader(0x2082c80c8, 0x0, 0x0, 0x0)
	/Users/untoldone/Source/go/src/github.com/tealeg/xlsx/lib.go:816 +0x327
github.com/tealeg/xlsx.ReadZip(0x2082c80c0, 0x0, 0x0, 0x0)
	/Users/untoldone/Source/go/src/github.com/tealeg/xlsx/lib.go:772 +0x6e
github.com/tealeg/xlsx.OpenFile(0x1b5930, 0x35, 0x2082c6068, 0x0, 0x0)
	/Users/untoldone/Source/go/src/github.com/tealeg/xlsx/file.go:41 +0x7a
main.main()
	/Users/untoldone/Source/go/src/bitbucket.org/gocodo/bloomsources/usgov/hhs/demo/main.go:10 +0x51
exit status 2
```

Would be nice to have support for this? Not sure what the difference is/ haven't done any research

**Comment by tealeg** [comment]
I join you in not knowing the difference.  If i had to guess I would say that's a dump of the data structures that are represented in the XLSX file, skipping the encoding/decoding step. 

Realistically though, we have more than enough work just getting XLSX working properly, I can't see myself spending time on this in the near future.

**Comment by ShawnMilo** [comment]
The `xlsx` package deals only with `.xlsx` files. An `xlsx` file is, literally, a zip file containing XML. You can run `unzip` on one and see the contents.

The `xlsb` format is a binary format, not compatible with the `xlsx` format. I did a quick Google search and didn't find any libraries that convert in either direction. Based on that, I'm assuming it's _way_ out of scope for this project.

You _can_ use Excel to convert your documents to `xlsx` format and then have more freedom in how you'd use them. Honestly, I'd never heard of `xlsb` before your comment, so hopefully you are able to do that.

If you have enough interest, consider doing some research and writing your own `xlsb` library for Go. I did another Google search and didn't see any. If there's enough need (even just for you), it might be worthwhile. That's why @tealeg created this package. :smile:
