### ISSUE TITLE
Unrecoverable panic on open file

### ISSUE THREAD

**Issue by fzerorubigd** [tealeg/xlsx#137]
#125

**Comment by fzerorubigd** [comment]
This problem is not about any particular file. the problem is, if I send a wrong file, I get a panic, and this panic is inside its own go routine, so there is no way for a developer to catch this. 

The main things : 

1- Bugs in your library should not crash my application, I can log them and I promise I report them. please understand that my app is not your lab or toy. 
2- Its a security risk. someone could craft a wrong file, and send it to my app. passing that to your library, and your library can not open it. so, my application is down.

**Comment by tealeg** [comment]
@fzerorubigd  OK, let's talk about this.  I'd like to have @ShawnMilo comment on this too.

I'm sorry your previous bug got closed with the resolution of the issue causing the panic, that's because the patch had a "fixes" in its text.  It's actually nicer for us to track this as a separate issue in any case.

Before I go further, I understand that this issue is annoying for you, but please also understand that we do not have a customer and client relationship.  @ShawnMilo and I work on this code in our spare time, and to my knowledge no-one else who contributed to this code did that with specific responsibility to support you - indeed we explicitly give no warranty or guarantee of functionality.  We try very hard to be helpful, and we will try to find a sensible resolution to your problem, but please refrain from making assertions like "my app is not your lab or toy", we have never done anything to your app, you decided to make use of the code.  This library is licensed under extremely permissive terms, if you don't like the decisions we make in maintaining it then we explicitly give you the right to fork the code and do as you wish.  

Now, let's try and find a sensible solution.  have the following suggestions:

1. We could try to introduce a debug flag that allowed us to switch behaviour between catching the panics or letting them stand.  As far as I know the approach to dealing with panics in goroutines is still to catch them per-routine, convert them into errors and pass them back on an error channel.  If we want to avoid losing salient data about the panic we'd also need to pass back the result of debug.Stack() or perhaps just call debug.PrintStack() as the first action when we catch the panic inside the goroutine.   I'd suggest that outside the goroutine we just convert the error back to a panic. 

2. Given that XLSX is a complex format, and I suspect that a user with malicious intent could always find a way to supply a document that would generate an untrapped error somewhere in the library, can I suggest that you might consider re-architecting your application a little to make it do the XLSX handling in a stand alone process rather that as part of the main application.

**Comment by HeinOldewage** [comment]
I think proper reporting of errors are important, a user of this library must be able to handle a broken file.

The cost of a `recover()` on my system is ~100ns and a `panic()` and `recover()` ~200ns. The library can panic and recover 5 million times and only add a second to the loading time of a sheet.
Adding the fact the a panic only occurs once(as it is fatal) adding a 200ns delay to report the problem in a manageable way seems worth while.
We can add simple error location reporting like follows

    if err:= recover(); err != nil {
     	   _,file,line,_ := runtime.Caller(3)
     	   err= fmt.Errorf("%v in %s:%v",err,file,line)
       }

The output will look something like
`Some err in C:/Go programs/src/Test/main.go:17`
And it only takes ~2μs.

We could add a debug flag, but this adds complexity to the code that maintainers would have to deal with, and hardly seems worth the performance it might gain us.

The only place I could quickly spot where this somewhat more elaborate error reporting will be required is in lib.go:620 and will only be called once for every xlsx file.

I could, with your approval, add this error reporting to pull request #128.

**Comment by tealeg** [comment]
@HeinOldewage I don't think the cost (time wise) is actually an issue - my point about costs was with regard to moving @fzerorubigd's use of xlsx into a separate process.

I'd rather we didn't conflate this with your other pull request, but I'd be happy to review a separate one.

**Comment by fzerorubigd** [comment]
@tealeg As the first part, I know that I am not your customer. I know about  the value of your time and works. but if you see the #125 i try to say my problem, but each time I get another response, not related to my problem and at the end you close it, without any notice.

I already have a fork of this in my company gitlab, without the go routine. and yaaay, my problem is solved. but I think it's my job to report it here too. If you think its not necessary and you don't like my contribution, simply close this one too.  

1- It is in separate process. but the problem is control over your application for a graceful shutdown vs. a crash. 
my worker allocate some resources, connect to a pool and some other things. in a graceful shutdown (that I implemented as a part of my workers) it return all this resources, unregister itself and some other things.  I want to load a xlsx file, the library can't. whatever the reason is. but the severity of this is depend on host application, not library. some time I can simply ignore it. the library is not in the position to decide, it can panic, but in a way that the host can catch it. the main question is here. why this library decide to panic in an unrecoverable way? why not the idiomatic way : ```return an error``` want to use the power of concurrency? its ok, you already wait for it via a channel, just catch the error and return it. 
2- Using a separate process is just a workaround, not a real solution.  I use it, but if library can not guarantee the security, then you should mention this inside readme.

**Comment by tealeg** [comment]
@fzerorubigd I want to reassure you that whatever happened I do take the point you're making seriously and I was happy to accept the patch.  I'm very glad that you want to raise bugs on the project also.  I hope 

With regards to statements on security and reliability.  I should be clear - I can't make those guarantees and nor can anyone else.  Microsoft themselves can't be sure that loading a malicious XLSX file in Excel couldn't cause an unexpected error condition or a breach of security (indeed it's well documented that such things occur from time to time).  In our case I have no direct control over the contents of the document, the go runtime and compiler used, the supporting libraries used by those tools, or the host OS used. and even if I did I don't think I could ever justifiably claim to have such a perfect understanding of the interactions of all those parts that I could make a guarantee or warranty of security and reliability.   

For what it's worth there is a clear statement about what you're entitled to expect in terms of quality of and functionality at the end of the README - it constitutes part of the license under which you are entitled to use the code:

THIS SOFTWARE IS PROVIDED BY Geoffrey Teale ``AS IS'' AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
