### ISSUE TITLE
xlsx: SetDateTimeWithFormat inconsistent arguments with SetDateTime

### ISSUE THREAD

**Issue by kardianos** [tealeg/xlsx#166]
SetDateTimeWithFormat takes a float64, while SetDateTime takes a time.Time. It would be reasonable to work around it but timeToExcelTime is not exported. I've copied locally for now.

**Comment by ShawnMilo** [comment]
@tealeg: It seems that we could just export `timeToExcelTime`, or have `SetDateTimeWithFormat` accept a `time.Time`. 

I'm in favor of the latter, as it follows the best practice in handling unicode -- accept anything, turn it into unicode immediately, and keep it as unicode always until export. The Excel date-as-float format is the "odd man out" in the software world, so I favor working towards eliminating it from all but the import and export functionality.

This would be a lot more work than simply exporting `timeToExcelTime`, but I think it would make the rest of the codebase nicer to work with, and more uniform, as @kardianos has pointed out.

**Comment by tealeg** [comment]
@ShawnMilo I agree that it makes sense.  The interface of the library should be go-centric not xlsx centric in it's typing as well.  That said and changes to the public interface should be made with care.  Normally in these cases I suggest adding the new way as a method with a different name, it could, however, be the case that we do that for the *old* way of doing things and provide an error (or docstring) pointing the end user at that old method.

**Comment by ShawnMilo** [comment]
There's already a `SetDate` and `SetDateTime`, and `Cell.NumFmt` is exported. I'd kind of rather see `SetDateTimeWithFormat` go away entirely, since it's redundant. 

Setting a value and setting the formatting are two distinct operations. If `SetDateTimeWithFormat` was my only choice, I'd have to replace the date every time I wanted to change the format, and vice versa. There's no value in it, and deleting code is good. :cake: 

@kardianos: Would using the existing `SetDateTime` and setting `Cell.NumFmt` be as good as (or better than) the changes discussed earlier?

@tealeg: Thoughts?

**Comment by kardianos** [comment]
@ShawnMilo That would probably be alright. It might be good to add documentation on the SetDateTime call referring to NumFmt too.
