### ISSUE TITLE
Panic when reopening an xlsx file that has been saved with the library

### ISSUE THREAD

**Issue by fourcube** [tealeg/xlsx#170]
I've created a little demostration, so you can reproduce the error. The XLSX files have been created with Excel 2013.

https://github.com/fourcube/xlsx-diagnosis

**Comment by ShawnMilo** [comment]
Thanks for doing all the work to make it easy for me to duplicate the problem. I do get the panic, so I will continue to investigate.

**Comment by fourcube** [comment]
No problem, thanks for responding so swiftly. If I should test anything with a larger example (unfortunately I cannot share this), just let me know.

**Comment by ShawnMilo** [comment]
I've already found the source of the problem, but I don't know what the solution is. If you're interested in helping investigate, the problem is [here](https://github.com/tealeg/xlsx/blob/master/lib.go#L470).

When this line is hit, the value of `i` during the first iteration of the loop is zero. So trying to access `cols[-1]` obviously can't work.

It seems like something is very wrong -- this should never work. However, I could be missing something, like maybe this assumes that the range beginning with `rawcol.Min` will always be greater than zero.

In your particular case, the `for` statement above this loop:

```go
for _, rawcol := range Worksheet.Cols.Col {
```

never runs with the original file because there's nothing in `Worksheet.Cols.Col`, so there's no error. So, evidently when the library rewrites the file it puts something there. Then reading the file `xlsx` wrote triggers the index error.

@tealeg: If you have time, I'd be grateful if you'd spend 10 minutes looking at this and provide advice. I think there is more context to this bug than I'm aware of, and I don't want to make a "fix" that masks the underlying issue or loses functionality.

**Comment by tealeg** [comment]
@ShawnMilo the root of the problem is that the source XLSX file doesn't have a cols element in sheet1.xml.

**Comment by tealeg** [comment]
@fourcube you should find that trunk nolonger exhibits this problem.  I've tested my fix with your code.  It now completes without error.

**Comment by ShawnMilo** [comment]
@tealeg: Thanks for explaining. I didn't know if was optional. I still have a lot to learn about the file format.

**Comment by tealeg** [comment]
@ShawnMilo me too! Even if you read the documentation, it won't fully prepare you for the variations that exist.

**Comment by fourcube** [comment]
Thank you very much. Everything works perfectly now!

**Comment by tealeg** [comment]
@fourcube my pleasure, thanks for raising the issue.
