### ISSUE TITLE
Stretching the column to the width of the widest cell value

### ISSUE THREAD

**Issue by orcaman** [tealeg/xlsx#189]
Hi,

I'm trying to control the width of a column, ideally what I would be able to do is to stretch the column width to the width of the longest cell value in the column (this is kind of like click the right edge of the top most column in excel). Is this possible to achieve?

Thanks

**Comment by carstn** [comment]
It's not built in to the package yet, but it would be a great feature if you added it! I believe you'll need to manually calculate the width of all glyphs in a given cell, referring to that cell's font. Do that for each cell in a column, and then set the column width.

You could probably find a simpler method to approximate it depending on your needs though.

**Comment by baconalot** [comment]
Related: maybe a quick fix is implementing a bool for "bestFit".
<col min="4" max="4" width="12" bestFit="1" customWidth="1"/>

**Comment by rbucker** [comment]
I'm following up because I wrote a similar issue many months ago and I came to the realization that it's impossible. In fact going back to 1987-ish I remember working on OS/2 and Windows and it was a challenge writing C/C++ code to compute the width. There may be some internals in the Microsoft APIs but that's one challenge... Give this a try and right click on the column header. There is no autoresize function.  Justy something to let you specify the width in a number. So the same is going to apply to your code too.  Personally I take the default font, multiple the number of chars in the formatted cell by 1.6 or 1.8.
