### ISSUE TITLE
Empty cells with formatting fails to parse

### ISSUE THREAD

**Issue by eproxus** [tealeg/xlsx#191]
A empty cell with Number format and a background color assigned fails to parse with the following error:

    strconv.ParseFloat: parsing "": invalid syntax

**Comment by ShawnMilo** [comment]
Please supply a simple spreadsheet that duplicates the problem. That will make it easy to replicate, and then fix.

**Comment by eproxus** [comment]
Here's a workbook that reproduces the error:
[Workbook1.xlsx](https://github.com/tealeg/xlsx/files/90723/Workbook1.xlsx)

**Comment by ShawnMilo** [comment]
Thanks for the file. I was able to open the file without an error. Sorry to ask again (I should have asked before), but please provide a simple, *complete* Go application which reproduces the error.

**Comment by eproxus** [comment]
Hi again, here's the program I used:

```go
package main

import (
	"fmt"

	"github.com/tealeg/xlsx"
)

func main() {
	excelFileName := "/path/to/Workbook1.xlsx"
	xlFile, err := xlsx.OpenFile(excelFileName)
	if err != nil {
		fmt.Print("Error")
	}
	for sheetN, sheet := range xlFile.Sheets {
		for rowN, row := range sheet.Rows {
			for cellN, cell := range row.Cells {
				fmt.Printf("%d %d %d %s\n", sheetN, rowN, cellN, cell.String())
			}
		}
	}
}
```

**Comment by eproxus** [comment]
Just realized that maybe `cell.String()` is causing the problem. Should I use something else to access number contents (and if so, how do I know when to)?

**Comment by ShawnMilo** [comment]
Yeah, if you use `cell.Value` instead of `cell.String()` it works.

First, the cell has a number format (click on the cell, then go to Format->Cell), and you'll see it is supposed to be a number. However, the value in the cell is "" (empty string). This causes a formatting error. If the cell was a string cell, it should be fine.

Secondly, (and this is an issue for the `xlsx` maintainers to discuss), the `FormattedValue` function returns a string, and no error. if it receives an error, then it passes the `err.Error()` (a string) back, and that's what you get in your code. Your code doesn't break, but you get Go error messages in your data.

@tealeg: Based on this, the "obvious" solution is that `FormattedValue()` (and therefore `String()`) should be changed to return `(string, error)` instead of just `string`. This is a big backwards-incompatibility issue, of course. I don't know if it's reasonable to consider this change due to the amount of code it will break, but it does seem to be more idiomatic to return `(string, error)` and force/allow the user to deal with bad data instead of letting it pass silently.

**Comment by eproxus** [comment]
Ah, that makes sense. Thanks for clarifying things.

I guess anything that returns something with an opinion about what it is (`String()`, `Number()` etc.) should return `(thing, error)` instead of printing stuff in the background? It would be much more Go-like.

**Comment by tealeg** [comment]
@ShawnMilo I'm starting to revise my views on backwards compatibility - the Go community has started to treat vendoring of code as the norm so I'm all for pragmatic improvements like that.

Are you keen to do that work yourself?

**Comment by ShawnMilo** [comment]
Sure, I'd be glad to make that change. I'll create a branch and notify you for review.
