### ISSUE TITLE
'trebuchet ms' can not be read correctly 

### ISSUE THREAD

**Issue by py-samsung** [tealeg/xlsx#199]
when my execl file is saved by font 'trebuchet ms' not helvetica.only one row can be read.other rows can not be read.please check this

**Comment by tealeg** [comment]
Would it be possible to provide a file exhibiting the problem?

**Comment by py-samsung** [comment]
i have sent a mail to you email,thanks a lot

**Comment by py-samsung** [comment]
[_meta.xlsx](https://github.com/tealeg/xlsx/files/162732/_meta.xlsx)

**Comment by tealeg** [comment]
@py-samsung so the problem is that your worksheet has a dimension value set to "A1" - currently we use this as a short cut for calculating the maximum extent of the sheet.  In this case it's clearly wrong.  

I will have to check the standard to see if we're horribly abusing this.

**Comment by tealeg** [comment]
@py-samsung just confirming - this bug is in the XLSX file not in the library.  The <dimension> element of    a worksheet has the following description according to the standard:

"This element specifies the used range of the worksheet. It specifies the row and column bounds of used cells in the worksheet. This is optional and is not required. Used cells include cells with formulas, text content, and cell formatting. When an entire column is formatted, only the first cell in that column is considered used."

The <dimension> attribute in your file contains the value "A1" which clearly states that only the 0th cell of the 0th row is in use.  If your file was generated from this library then we have a valid bug.  If not then you need to look at the tool that generated it.

**Comment by tealeg** [comment]
Thanks at @py-samsung !
