### ISSUE TITLE
date type of cell could not be identified for the xslx file

### ISSUE THREAD

**Issue by ericzzy** [tealeg/xlsx#226]
I want to automatically get the cell type per the cell value,  it works well when the actual cell value is numeric or string, but when the cell value is of date or datetime, it is incorrectly to be identified as numeric. So my question is that how can I get the correct cell type for date/datetime cell value? thanks.

**Comment by klniu** [comment]
Cell.Type can't determine the type of the value, because the date and time are stored as float which has  a numfmt to indicate how to render the value, such as "yyyy-mm-dd" to render as a date. So the library can't do this for you because there are only has 49 builtin numfmts which can't cover all the formats. I think the solution is getting Cell.NumFmt and according that to determine if it is a date. For example, check if the cell.NumFmt is one of "yyyy-mm-dd", "yy-m-d" and so on.
