### ISSUE TITLE
Stream Reading?

### ISSUE THREAD

**Issue by lalvarezguillen** [tealeg/xlsx#346]
[Issue 338](https://github.com/tealeg/xlsx/issues/338) addressed reading the XLSX's head without having to load the entire spreadsheet in memory, which is game changing

But that does not help when you want to iterate through a larger portion of a spreadsheet (or full spreadsheet) without loading the entire spreadsheet into memory.  I guess you can call it Stream Reading.

Is Stream Reading in the scope of this project?

**Comment by ryho** [comment]
I’m glad some else found that feature useful!

I looked into implementing stream reading, but it was going to be tricky, and I was able to do everything my company needed by implementing only partial reads, though we did need full stream writing. I’ve found that the amount of time and memory needed to open the largest files that we support is annoying but acceptable for our use case. Some upstream code limits us to 16MB files, and the library was good enough for files of that size.

We use this library to allow users to do import and export of their data. Our import flow is asynchronous, the browser will post a file and the server will create a background thread to run the import. The browser will then poll for the status of the import until it is finished. This allows the user to know the status of the import even if they close the browser or have flaky internet. This flow allows the imports to work without stream reading, you could consider implementing something like that if your use case is similar. Our export flow is not asynchronous, so we rely on Stream writing to ensure that the network connection stays open, though this could be improved by being made asynchronous as well. I found that implementing stream writing was much faster than switching to async exports would be for us.

If you’re interested in implementing stream reads, I’d suggest you look at how I implemented partial reads. One could call it hacky, but the implantation is always correct. When the XML file containing a sheet is about to be opened, it uses Go’s Stream XML reading to read through to the Nth row end tag, then appends a fake XML sheet ending and passes this smaller XML sheet through the same XLSX opening logic as before. Go’s Stream XML parsing is very barebones, it basically only supports “go to the next tag and tell me its name”. If you create structs that match the structure of the data in the XML file, Go’s non-streaming XML library will use reflection to fill the data into structs for you. The logic to read with only the Stream XML reader would be a lot of trouble and very unmaintainable. The only workable solution is to use XML streaming to find more row tags and then use the normal XML library to parse them out into xlsxRow structs.

The code to open XLSX files would have to be edited quite a bit to accomplish a second partial read while being sure you haven’t broken anything along the way, though it would be possible. Many points in the code assume they will only be run once per file at its opening, you’d have make sure you worked through all of these assumptions. You could basically pull out the code that handles the rows, and edit it so that it could be run a second time with more row XML tags.

Another issue is that right now the library just gives you an array of rows and columns. You’d need to figure out a way to interact the library that still makes sense while stream reading. Maybe when you request the next 100 rows, it just replaces all the previous rows with the next ones. I think that would make sense.

**Comment by lalvarezguillen** [comment]
Thanks for the insight ryho!

We use a similar architecture (asynchronous job for XLSX reading), but we see significantly larger XLSX files, that require way too much memory if read in full.

We used Python this far for data ingestion, and one of its XLSX libraries allowed us to yield rows of the XLSX without loading the entire file into memory. I'll try to replicate and report back, XML streaming does seem like the way to go
