### ISSUE TITLE
Cell.String() trim leading 0s

### ISSUE THREAD

**Issue by sganon** [tealeg/xlsx#418]
When your cell contains a string formatted like `'00123456` calling Cell.String() on it return "123456". Using Cell.Value solves the problem, but I think this not the correct behaviour of the String function.

**Comment by sganon** [comment]
Actually `xml.Decode()` already returned trim value [here](https://github.com/tealeg/xlsx/blob/f1917addaa283ecd881e40b48173544d4145ea67/xmlWorkbook.go#L207). So now I'm wondering how do you get back the correct Value afterwards, and shouldn't be possible to check if `Cell.String() != Cell.Value` in this case ?

**Comment by ryho** [comment]
This is the correct behavior. I have gone to great lengths to ensure this library replicates the behavior of Excel for string formatting as much as possible. If you do not want the leading zeros stripped, you’ll need to change the cell formatting to string instead of general.

It’s been a while since I touched the library, so that may not be the correct XLSX terminology, but there is an easy way to accomplish what you want. That’s what I do when exporting UPCs.
