### ISSUE TITLE
Validate the file format

### ISSUE THREAD

**Issue by pruse2402** [tealeg/xlsx#448]
Can someone help me how to validate whether the uploading file is xlsx and if they are uploading someother file format then it should throw an error.
It should allow only xlsx file

**Comment by ryho** [comment]
There isn’t a specific error for that.

An XLSX file is just a ZIP file with lots of XML files in it. So if you try
to open a random file, most likely you’ll get an invalid zip file error
from the ZIP parser. That’s a Go standard library and there’s a constant in
that package with the exact error that you can compare against. But if the
file is a valid zip, but doesn’t have the right xml files in the right
directories (because it’s a regular ZIP or it’s DOCX, etc), you’ll get one
of many different errors that will be hard to differentiate.

In my program, I only tell the user to use the correct file type is the
file extension is  it XLSX, and if the library returns an error I just give
a generic “something went wrong” message. If they’re editing the file
extension to be XLSX when it’s not, then it’s their fault anyway.
