### ISSUE TITLE
How to read password protected xls file?

### ISSUE THREAD

**Issue by cyantarek** [tealeg/xlsx#462]
How to read password protected xls file?

**Comment by AlmogBaku** [comment]
@tealeg any idea?

**Comment by tealeg** [comment]
@AlmogBaku two things:
1. this library only reads XLSX files not the older XLS format
2. the way excel password protection works means that you probably don't need to provide the password at all.  The enforcement is application level - within a Sheet you'll find a `sheetProtection` element that contains the hashed form of the password and some configuration options for how an application should work.  Any XLSX reader that doesn't read this data can and will do what it likes without enforcing that policy.

**Comment by ewest-FBi** [comment]
@tealeg it may surprise you, but it appears that "probably" lost in this case, as attempts to open password-protected files fail with: "OpenFile: zip: not a valid zip file"

**Comment by tealeg** [comment]
@ewest-FBi there are two different password systems for excel. An old one that relied on the software checking against a hash in the file. That was basically completely insecure and this library just ignored it (because you could still read the file). The new way seems to involve encrypting the file itself (better!) but I've not looked into it in any depth.
