### ISSUE TITLE
feat: Read specific sheets

### ISSUE THREAD

**Issue by judwhite** [tealeg/xlsx#480]
I have a 2MB file I only need to read two sheets from. I added some quick code to `lib.go` in `readSheetsFromZipFile` to filter the sheets needed, it looks something like this:

```go
if rawsheet.Name != "xxx" && rawsheet.Name != "yyy" {
    sheetChan <- &indexedSheet{Index: i, Sheet: &Sheet{File: file}}
    continue
}
```

Benchmark results:

```
BenchmarkOpenFile-28                   1        22947001200 ns/op  # unfiltered
BenchmarkOpenFile-28                  54           19685157 ns/op  # filtered
```

In people terms that's 22s and 19ms :)

Would you be open to a PR that adds functions to return a `map[string]*Sheet` in the case only a few sheets are needed?

Any guidance for how you'd like the API to look (for example, supporting file names, `io.Reader`, `[]byte`, and row limits)?

Thanks!

**Comment by tealeg** [comment]
Hi @judwhite 

Firstly, yes, I'd be very open to a PR to add such a feature.  The trickiest part is supporting a save when only a few sheets have been opened.  That's tricky enough that I'd propose not allowing such a save for now.

Beyond that, I've actually been thinking about reworking the `Open..` functions, perhaps taking some kind of config instead of having a dedicated public function for each case.  As we add orthogonal functions we'll keep adding more and more functions, and I think that's a mess.
