### ISSUE TITLE
merge cell bug

### ISSUE THREAD

**Issue by p410342078** [tealeg/xlsx#483]
merge cell  be overwritten
![image](https://user-images.githubusercontent.com/49271307/67179934-91887400-f40a-11e9-92f5-08311488dd9e.png)
![image](https://user-images.githubusercontent.com/49271307/67179949-9d743600-f40a-11e9-95d1-774e037ae907.png)

**Comment by tealeg** [comment]
@p410342078 OK, I'll look into it.  Very odd because merging shouldn't affect the underlying cell data.

**Comment by p410342078** [comment]
I found the usage ，


Merge several cells and execute several times " row.addcell"





------------------ 原始邮件 ------------------
发件人: "Geoffrey J. Teale"<notifications@github.com>;
发送时间: 2019年10月21日(星期一) 下午2:40
收件人: "tealeg/xlsx"<xlsx@noreply.github.com>;
抄送: "(8D14M1) 活动中心"<410342078@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [tealeg/xlsx] merge cell bug (#483)




@p410342078 OK, I'll look into it.  Very odd because merging shouldn't affect the underlying cell data.

**Comment by tealeg** [comment]
I have tested this on the master branch, there is no bug.  You are creating multiple contiguous merge definitions.  In the output your merge cells will look something like this:

```xml
  <mergeCells count="4">
    <mergeCell ref="A1:C1">
    </mergeCell>
    <mergeCell ref="B1:D1">
    </mergeCell>
    <mergeCell ref="C1:E1">
    </mergeCell>
    <mergeCell ref="D1:F1">
    </mergeCell>
</mergeCells>
```

Because these mergeCell definitions overlap, Excel is propogating the value of the first merge cell into one long, contiguous merged cell.  If you unmerge that cell you'll see that the underlying values are still in place.  Again, the underlying XML looks like this:

```xml
  <sheetData>
    <row r="1">
      <c r="A1" s="1">
	<v>
	1</v>
      </c>
      <c r="B1" s="1">
	<v>
	2</v>
      </c>
      <c r="C1" s="1">
	<v>
	3</v>
      </c>
      <c r="D1" s="1">
	<v>
	4</v>
      </c>
      <c r="E1" s="1" t="s">
      </c>
      <c r="F1" s="1" t="s">
      </c>
    </row>
  </sheetData>
```

So as I say, there's no bug, the library is doing exactly what you asked it to do, and Excel is applying it correctly.
