### ISSUE TITLE
Blank cells considered nil in ForEachFunc

### ISSUE THREAD

**Issue by mariaefi29** [tealeg/xlsx#536]
Dear developers. 

When I use ForEachFunc iterator it ignores empty cells, because they are considered nil. However, it is important for me to treat them as empty strings. Is there a workaround? I have been stuck with it for quite a long time. 

I have managed not to use the ForEachFunc and have written something like:

```
	res := make([]string, 0, r.data.MaxCol)

	for i :=0; i < r.data.MaxCol; i++ {
		c := row.GetCell(i)
		val, err := c.FormattedValue()
			if err != nil {
				res = append(res, err.Error())
			} else {
				res = append(res, val)
			}
	}
```
Unfortunately, this function appends empty strings automatically at the end of the row, because I use MaxCol in for clause. I couldn't find the way how to get just the number of cols in the row :( the value is unexported :( 

I would be very grateful if you could help me.

**Comment by tealeg** [comment]
Hi @mariaefi29 I think I need to revisit the design of the `ForEach...` functions.  Skipping the `nil` cels is by design, but I think I need to have it provide more information and perhaps have optional behaviour.  

As this functionality is only available in the `master` branch right now, and not in the released version you could try explicitly using version 2.0.1 instead, but I will attempt to address this quickly as it's an important part of the new API.

**Comment by mariaefi29** [comment]
Dear @tealeg,

Thank you very much!

PS. Also thank you for pointing out the released version! My bad) I guess I have started updating too soon.

**Comment by tealeg** [comment]
@mariaefi29 I'm actually really grateful that people run the "in development" version so that things like this get exposed.
