### ISSUE TITLE
Add support for removing columns

### ISSUE THREAD

**Issue by tealeg** [tealeg/xlsx#600]
Currently it's not possible to remove columns from a sheet.

Any implementation of this should take special care to do the following:

1. shift cells in following rows or columns up or left as appropriate. 
2. think about the impact on column styles (`Cols` internally speaking).

**Comment by vladimirfilin** [comment]
Thank you so much!
func (s *Sheet) RemoveRowAtIndex(index int) works well now.

**Comment by tealeg** [comment]
Yes, but removing columns is a harder task.

**Comment by derlinkshaender** [comment]
It just occurred to me that the solution might not be as simple as removing a row or a column and shifting accordingly if you want to mimic the behavior of an application like Excel or LibreOffice.
If you remove a column or a row with these, not only will the cells get shifted, but also **all** formulas are rewritten, if necessary. Suppose you have a formula like `=B2/100*$B$5` in a cell in row 2 (numeric index 1 in the package, because base zero). Now you remote row 4. If you then look at the cell again, the formula will read `=B2/100*$B$4`!
Not taking this behavior into account may lead to some very hard to find bugs in the sheet logic. Correct me if I'm wrong, but I think that any functionality that adds or removes cells should state this very clearly in the comment to provide a way to rewrite formulas (would be glad to help with this, though I don't know if my knowledge fits this requirement).

**Comment by vladimirfilin** [comment]
If I have correctly captured the spirit of this library in a few days working with it, there is no purpose to recreate the behavior of MS Excel in Go. My opinion is that we write data from Go into xlsx files as we see fit. And we are responsible for the result, not this library. Thus, if we have deleted the column by mistake and have not updated the formulas ourselves, it is our mistake. In MS Excel it is the same.
Create a simple formula for C1: =A1+B1

![Screenshot_1](https://user-images.githubusercontent.com/60051416/87233316-e3c15900-c3ce-11ea-9698-4c1a3f430f24.jpg)

And then delete column A1. We get a wrong reference error:

![Screenshot_2](https://user-images.githubusercontent.com/60051416/87233325-f0de4800-c3ce-11ea-80b3-07069137e40f.jpg)

I’m for giving the opportunity to delete!
But the Author has priority, of course.

**Comment by derlinkshaender** [comment]
Vladimir, personally couldn't agree more with you. I also use the package to _create_ xlsx files. So if something goes haywire, I am the one responsible for it. 😉 I just edited my comment to improve my wording (I missed an "or"). I'm all for having functions to remove rows and columns. I just don't want anybody to be surprised when handling existing files. The difference between my scenario and you example is that in you example you get a clear message that something went wrong. In my example the formula **could** still work, but produce a completely different result. As I personally know people that used to calculate medical stuff with Excel, I am sure you understand my caution. Thanks for you feature request, will be glad to help as good as I can.
