### ISSUE TITLE
Writer gives broken Excel File

### ISSUE THREAD

**Issue by pgundlach** [tealeg/xlsx#63]
Using the following file with version d6607c512cf8c1083a9b5ec1efd7e1ccfb1832c8 I get a broken Excel file. How can I write multiple rows?

````
package main

import (
	"fmt"
	"github.com/tealeg/xlsx"
)

func main() {
	var file *xlsx.File
	var sheet *xlsx.Sheet
	var row *xlsx.Row
	var cell *xlsx.Cell
	var err error

	file = xlsx.NewFile()
	sheet = file.AddSheet("Sheet1")
	row = sheet.AddRow()
	cell = row.AddCell()
	cell.Value = "I am a cell!"

	row = sheet.AddRow()
	cell = row.AddCell()
	cell.Value = "I am a cell!"

	err = file.Save("MyXLSXFile.xlsx")

	if err != nil {
		fmt.Printf(err.Error())
	}
}
````

**Comment by kardianos** [comment]
@tealeg You can use MS One Drive (Free to use, can use from Chrome on Linux) to test XLSX output.

**Comment by tealeg** [comment]
Thanks @kardianos, I actually started doing just that over Christmas!  It's still not perfect, in that it doesn't tell me anything about what is wrong with the files, but at least it gives me *some* indication.

**Comment by BrianMMcClain** [comment]
FWIW, seeing the same on:

OS X 10.10.2
Microsoft Excel for Max 2011 v14.4.7 (141117)

And seeing the following logs after a repair

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Repair Result to test 06308.xml</logFileName><summary>Errors were detected in file 'Macintosh HD:Users:brianmcclain:Documents:test.xlsx'</summary><removedParts summary="Following is a list of removed parts:"><removedPart>Replaced Part: /xl/worksheets/sheet1.xml with XML error.  Load error. Line 2, column 698.</removedPart></removedParts><removedRecords summary="Following is a list of removed records:"><removedRecord>Removed Records: Document Theme from /xl/workbook.xml (Workbook)</removedRecord></removedRecords><repairedRecords summary="Following is a list of repairs:"><repairedRecord>Repaired Records: Format from /xl/styles.xml (Styles)</repairedRecord></repairedRecords></recoveryLog>
```

And the result is an empty file. I took a look at @nadoo's changes, however while the data was showing, unfortunately in my specific use case, styling is a requirement. I'd be happy to provide any additional information if you'd like!

**Comment by lattwood** [comment]
I'm getting the same issue as @BrianMMcClain

**Comment by yupengfei** [comment]
I got the same error again，but what I have is a Chinese version. What can I do to help?

**Comment by ShawnMilo** [comment]
@yupengfei The Chinese  version of what, OSX? 

I confirmed that, using the file generated by the original post in this issue, I get an error:

    "MyXLSXFile.xlsx" can't be opened.

No useful errors, though.

**Comment by tealeg** [comment]
I believe that on Mac OS X it's possible to see more information about failures in log files that Excel writes.  Presumably in ~/Library/Logs/ someplace, but I don't recall all the details.

**Comment by yupengfei** [comment]
@ShawnMilo Sorry to reply late, we use Chinese version of MS office. I have tried OSX, it can not open generated xlsx files. But MS Office can open it normally after repair it. MS Office privide some error message in Chinese.

**Comment by ShawnMilo** [comment]
@tealeg:

Thanks for the tip. I couldn't get any debug info from Numbers, but I did a lot of playing with two spreadsheets, working and non-working by copying bits from one to the other. I did find a solution.

In `workbook.xml`, in the `workbook` tag, there is this: `xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"`. It turns out that adding this into the `workbook` tag as well fixes the file:

`xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"`

I'm having trouble finding where to add this to the code (grep brings back too many selections). I can narrow it down, but I wanted you to have a look in case this is a bad idea for some reason.

**Comment by tealeg** [comment]
@ShawnMilo I think the issue is that the normal XML marshalling in Go doesn't allow for additional namespaces to be defined in the root element of the document.   The default namespace is set up by the tags on the XMLName field of the structs we marshal to/from.  

Because of this restriction, I believe the code currently has cases where we set the namespaces on the elements in the document, that belong to namespaces other than the default, directly.  That should be valid XML, but it may not be good enough for Excel.  There does seem to be some work going on to address this [that may turn up in Go 1.5]( https://github.com/golang/go/issues/9519 ).  Personally I'd like us to stick to using Go's XML marshalling, but if needs be I wouldn't be opposed to temporarily pulling in development versions of the library if it really is useful.   Obviously with a view that these would be removed once the functionality is generally available.
