### ISSUE TITLE
heap issue

### ISSUE THREAD

**Issue by tharun-d** [tealeg/xlsx#640]
can someone guide me to resolve this issue

goroutine 35 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:363 fp=0xc4236a6cc8 sp=0xc4236a6cc0 pc=0x455100
runtime.(*mcache).nextFree(0x7f8ce21f36c8, 0x6, 0xc50ce059a0, 0x0, 0xc42035a400)
	/usr/local/go/src/runtime/malloc.go:555 +0xa9 fp=0xc4236a6d20 sp=0xc4236a6cc8 pc=0x411559
runtime.mallocgc(0x20, 0xcf3780, 0x1, 0x12)
	/usr/local/go/src/runtime/malloc.go:710 +0x79f fp=0xc4236a6dc0 sp=0xc4236a6d20 pc=0x411eaf
runtime.makeslice(0xcf3780, 0x2, 0x2, 0x1, 0x1, 0xdf5a40)
	/usr/local/go/src/runtime/slice.go:61 +0x77 fp=0xc4236a6df0 sp=0xc4236a6dc0 pc=0x441047
strings.genSplit(0xc8fce2, 0xc, 0xe53d73, 0x1, 0x0, 0x2, 0x0, 0x0, 0xe)
	/usr/local/go/src/strings/strings.go:246 +0x6b fp=0xc4236a6e50 sp=0xc4236a6df0 pc=0x4dce7b
strings.Split(0xc8fce2, 0xc, 0xe53d73, 0x1, 0x12, 0xe54628, 0x3)
	/usr/local/go/src/strings/strings.go:298 +0x5b fp=0xc4236a6ea8 sp=0xc4236a6e50 pc=0x4dd29b
github.com/tealeg/xlsx.parseXMLTag(0xc8fce2, 0xc, 0xe54628, 0x3, 0xc8fce2, 0xc, 0x1260b60)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/xmlWorksheet.go:515 +0x4e fp=0xc4236a6f08 sp=0xc4236a6ea8 pc=0xbbc6de
github.com/tealeg/xlsx.emitStructAsXML(0xdf5a40, 0xc50cbe1868, 0x199, 0xc6a5f9, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/xmlWorksheet.go:565 +0x301 fp=0xc4236a77e0 sp=0xc4236a6f08 pc=0xbbcbe1
github.com/tealeg/xlsx.emitStructAsXML(0xdf5c80, 0xc420091310, 0x199, 0xe545b0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/xmlWorksheet.go:622 +0xda3 fp=0xc4236a80b8 sp=0xc4236a77e0 pc=0xbbd683
github.com/tealeg/xlsx.emitStructAsXML(0xcc3ea0, 0xc420091310, 0x16, 0xe545b0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/xmlWorksheet.go:538 +0x164b fp=0xc4236a8990 sp=0xc4236a80b8 pc=0xbbdf2b
github.com/tealeg/xlsx.(*xlsxWorksheet).WriteXML.func1(0xc420bf3cc0, 0xc420bf3cc0, 0xd)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/xmlWorksheet.go:743 +0xf1 fp=0xc4236a8c00 sp=0xc4236a8990 pc=0xbc3c11
github.com/tealeg/xlsx.(*Sheet).ForEachRow(0xc4204d0000, 0xc4209247e0, 0xc420594d98, 0x1, 0x1, 0xe5a385, 0x9)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/sheet.go:180 +0x1d5 fp=0xc4236a8c68 sp=0xc4236a8c00 pc=0xbafc15
github.com/tealeg/xlsx.(*xlsxWorksheet).WriteXML(0xc42129d560, 0xc4203f2120, 0xc4204d0000, 0xc4203bc420, 0xc4212473b0, 0x0, 0x0)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/xmlWorksheet.go:737 +0x310 fp=0xc4236a8f48 sp=0xc4236a8c68 pc=0xbbe500
github.com/tealeg/xlsx.(*Sheet).MarshalSheet(0xc4204d0000, 0x124be40, 0xc4200901e0, 0xc4212473b0, 0xc4203bc420, 0x0, 0x0, 0x10)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/sheet.go:847 +0x2d5 fp=0xc4236a8fe8 sp=0xc4236a8f48 pc=0xbb25c5
github.com/tealeg/xlsx.(*File).MarshallParts(0xc4203ee000, 0xc420090140, 0x1000, 0xc4202ae000)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/file.go:472 +0x878 fp=0xc4236a9780 sp=0xc4236a8fe8 pc=0xba5f78
github.com/tealeg/xlsx.(*File).Write(0xc4203ee000, 0x124cda0, 0xc42013c380, 0x124cda0, 0xc42013c380)
	/home/ec2-user/Repo/nsdcserverside/src/github.com/tealeg/xlsx/file.go:158 +0xc6 fp=0xc4236a97e8 sp=0xc4236a9780 pc=0xba3426
nsdcsectorservice/handler.renderExcel(0x1253780, 0xc42013c380, 0xc4203ee000, 0xe5c027, 0xb)
	/home/ec2-user/Repo/nsdcserverside/src/nsdcsectorservice/handler/kbhandler.go:51 +0x173 fp=0xc4236a9848 sp=0xc4236a97e8 pc=0xc31933
nsdcsectorservice/handler.ExportTrainerSpecExcel(0x1253780, 0xc42013c380, 0xc4204cfd00)

**Comment by tealeg** [comment]
The issue is within an attempt to split an XML tag string using the standard library `strings.split` function.   The code in the `parseXMLTag` function that makes that call could certainly be more careful about checking what it's handling, but I am surprised that it would result in an error - in particular, this stack trace points to an underlying malloc (memory allocation).  

Is this an especially large spreadsheet you're handling?

**Comment by tharun-d** [comment]
yes from db to excel huge data

**Comment by tealeg** [comment]
@tharun-d the XML in question is internal to the XLSX format itself.  It's likely this is in effect resulting from memory exhaustion, but I cannot be sure just by looking at the stack trace.  

Are you using the DiskVCellStore backend for the library?  That should help limit the memory usage (although the full effect can only be seen by using the current HEAD of master, as I haven't yet released it).

**Comment by ecarter202** [comment]
Would this be of the same issue? The file I am running is of 50k rows.
There are 2 points I'd like to make in my case:

1. The larger the file processed, the more probable this error will be raised.
2. The error is inconsistently thrown, by which I mean sometimes it is thrown minutes from me starting to process a file, and sometimes it is hours.

I haven't checked my memory usage during such processing, but it seems that a memory leak could be the cause since the number of open applications, other processes running, etc are not always the same: hence an 'inconsistent' error thrown.

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x106b6d2]

goroutine 15 [running]:
github.com/tealeg/xlsx.(*xlsxStyleSheet).addFont(0xc000136000, 0x1388340, 0x2, 0xc0005326e8, 0x7, 0x137f934, 0x1, 0x137f932, 0x1, 0xc006757d58, ...)
	/Users/jimbo/Code/go/src/github.com/tealeg/xlsx/xmlStyle.go:273 +0x259
github.com/tealeg/xlsx.handleStyleForXLSX(0xc000137040, 0x0, 0xc000136000, 0x0)
	/Users/jimbo/Code/go/src/github.com/tealeg/xlsx/sheet.go:417 +0x25a
github.com/tealeg/xlsx.(*Sheet).makeXLSXSheet(0xc000116960, 0xc13f57b6b0, 0xc000136000, 0xc0062106c0)
	/Users/jimbo/Code/go/src/github.com/tealeg/xlsx/sheet.go:319 +0x1630
github.com/tealeg/xlsx.(*File).MarshallParts(0xc0000783c0, 0x5fa47824, 0x2e4e7c1b, 0x5fa47824)
	/Users/jimbo/Code/go/src/github.com/tealeg/xlsx/file.go:273 +0x345
github.com/tealeg/xlsx.(*File).Write(0xc0000783c0, 0x13da120, 0xc23efae038, 0x1b6, 0xc23efae038)
	/Users/jimbo/Code/go/src/github.com/tealeg/xlsx/file.go:135 +0x45
github.com/tealeg/xlsx.(*File).Save(0xc0000783c0, 0xc2f6b8b590, 0x2b, 0x2, 0x2)
	/Users/jimbo/Code/go/src/github.com/tealeg/xlsx/file.go:126 +0x8d
main.propWorker(0xc000078360, 0xc00775a820)
`

**Comment by tealeg** [comment]
Please can you retry with the freshly cut v3.2.1 release using the `DiskVCellStore` backend.  I'm not certain it will fix it, but It might and I'd be interested in the results.  Note that this backend now has some fairly strict rules about when you're allowed to set values on cells/rows that are the last ones you "got" from the cell store - if you attempt to set something on a row/cell that you've held a reference to, and subsequently have requested a new one, you'll get a clear, and deliberate panic from the library.   This is the cost of having strict limitations on memory usage within the current design of the library.

**Comment by Oxeygen-K** [comment]
@tealeg  Hello, is there a way to reduce the memory after exporting files based on v1.0.5. When I use v1.0.5 to export 30w data in Excel, it can be exported in about 9 seconds, but the memory will consume about 1.7g; when I use the latest v3.2.1 version, the same logic consumption memory continues to grow to 5g or more, and it is long The time is not exported. Using the xlsx.UseDiskVCellStore(file) method, the memory will not increase continuously and will not reach 1G, but it has not been exported for a long time

**Comment by tealeg** [comment]
@Oxeygen-K no, there's no option in the v1.x branch other than in memory. Clearly the weight of extra functionality and complexity has bloated things in V2 and V3 - DiskVCellstore trades memory space against performance. In theory we could make that trade off tunable by exposing the variable that sets the size of the diskv cache. That's probably the next step, but it's not a magic bullet.

  Originally I tried to find a balance by swapping data in and out one row at a time, but that still allowed some sheets, with high numbers of columns, to consume vat amounts of memory.

At this point I'm resigned to the fact that a better fix the these problems requires a redesign of the core of the library (it was never designed to do this). That would require API level changes and a tonne of work that I did have time to do, so at this point I'd probably just advise you to take a look at one of the other go Xlsx libraries - several have been created in the decade since this one was.
