### ISSUE TITLE
SetColAutoWidth has an issue

### ISSUE THREAD

**Issue by geraldstanje** [tealeg/xlsx#658]
Hi,

there is some issue with: SetColAutoWidth. when i start with i == 0 it has an error - the xlsx file is corrupted. when i do: sheet.SetColAutoWidth(1, xlsx.DefaultAutoWidth) it sets the first col. also sheet.SetColAutoWidth(5, xlsx.DefaultAutoWidth) corruptes the xlsx file.

```
file := xlsx.NewFile()
sheet, err := file.AddSheet("Demo")
if err != nil {
	return nil, nil
}
defer sheet.Close()
header := createHeader() // returns 5 col names

row := sheet.AddRow()
row.SetHeight(16)

for i, headerCol := range header {
	cell := row.AddCell()
	cell.Value = headerCol
	sheet.SetColAutoWidth(i, xlsx.DefaultAutoWidth)
}
```

**Comment by xiefulaithu** [comment]
i face the same issue.

when call sh.SetColAutoWidth(1, xlsx.DefaultAutoWidth), what the func really modify is the 2nd col.

the version i use is : v3.2.3

**Comment by xiefulaithu** [comment]
@tealeg

**Comment by njern** [comment]
Ran into this issue as well. 

I think the problem is that `func (s *Sheet) SetColWidth(...)` assumes column indexes start from `1` while `SetColAutoWidth` looks up the width of cells using zero-based column indexing. 

Using `v3.2.3`, calling `sheet.SetColWidth(1, 1, 20)` sets the width of column A.

However, when calling `sheet.SetColAutoWidth(1, xlsx.DefaultAutoWidth)`, the function will look for the widest cell in column B and set the width of column A accordingly which is clearly not what **should** be happening.

**Comment by kevinabrandon** [comment]
@tealeg I ran into this issue so after pulling the latest commit which has your fix I found my code was now panicking.  Apparently you're now expecting a 1 based index in SetColAutoWidth. If you give it zero it'll panic trying to get something at index -1.  Maybe this is the intention, but it sure didn't seem like it according to the comments.

It seems that there is a general issue for this project that at times it expects a zero based index and others a one based index and I'm a bit confused as to when I should use one over the other.
