### ISSUE TITLE
时间问题

### ISSUE THREAD

**Issue by adongroom** [tealeg/xlsx#68]
excel内的时间导入mysql数据库都是0001-01-01 00:00:00

**Comment by ShawnMilo** [comment]
@samoin What features are you most interested in? Are you available to contribute to the project? I've just been added as a maintainer, and I'm going through all the issues.

Also, regarding the original item in the ticket, what do you mean by "export to mysql"? Please explain the steps I need to take to duplicate the problem. As it is, I don't know how to begin working on this ticket.

**Comment by samoin** [comment]
@ShawnMilo i just translated the question， in chinese ，i think he means when he use this to export the values of all cells， he found the date typed value was not what he want ，it was 0001—01—01 00：00：00.

**Comment by ShawnMilo** [comment]
@samoin: Thanks for the assistance. I'd want a sample file with a minimal program to show the problem, along with the expected output to do something about it. If you are interested, please reply to  adongroom asking for this and ask him to post to this issue. Since I don't understand the issue, I'm unable to work on it, and I'd like to fix it.

**Comment by tealeg** [comment]
No further comment in more than 4 years.  Closing this as "out of date".
