### ISSUE TITLE
we use this xlsx.FileToSlice method to decode .xlsx file, but it consumes a lot of memory

### ISSUE THREAD

**Issue by QvodSoldier** [tealeg/xlsx#700]
Hi, We call the ```xlsx.FileToSlice``` method to parse files uploaded by customers

 <https://github.com/erda-project/erda/blob/develop/pkg/excel/decode.go> 
```
func Decode(r io.Reader) ([][][]string, error) {
	tmpF, err := ioutil.TempFile("", "excel-")
	if err != nil {
		return nil, err
	}
	if _, err := io.Copy(tmpF, r); err != nil {
		return nil, err
	}
	data, err := xlsx.FileToSlice(tmpF.Name())
	if err != nil {
		return nil, err
	}
	return data, nil
}
```

It will run normally until someone uploads an xlsx file with many null values, and these values ​​are not needed.

We found that the xlsx file is only 2M, but this method requires nearly 2G of memory to complete the decoding.

We unzipped the file and found that xl/worksheets/sheet1.xml has 757,875 lines, and most of them are null values. like this
```
<c r="H68" s="50"/>
<c r="I68" s="50"/>
``` 
These null values ​​are distributed in different rows and different columns. Therefore we feel that decoding this unusual xml file consumes a lot of memory. I was wondering if we have some way to prevent this from happening

Below is our screenshot
![image](https://user-images.githubusercontent.com/35135086/116523774-2c6be380-a909-11eb-8fca-157cb583aa64.png)
![image](https://user-images.githubusercontent.com/35135086/116523872-4b6a7580-a909-11eb-8159-8d6ddba9756d.png)

**Comment by tealeg** [comment]
Hi.  This is actually a really common problem and touches on one of the biggest issues this library has.

Anyhow, just to talk through this a bit.  Part of the problem is that those cells aren't actually NULL - they're indicating they are string values, and the s="50" part of them is referring to the 50th element in the shared string table.   It's probably the case that they're empty strings - but we don't know that until we look up the value, and this library is completely naive about that, so it just loads the XML into memory and deals with it when you ask. 

Right now, the best solution we have to this kind of problem is to use the DiscVCellStore as a backend instead of the MemoryCellStore.  This mechanism tries to limit memory usage by only holding a single row in memory at any given time (give or take a little caching).  The way to do this is to pass [xlsx.UseDiskVCellStore](https://pkg.go.dev/github.com/tealeg/xlsx/v3#UseDiskVCellStore) as the `FileOption` parameter of `FileToSlice`.  Be warned though, this technique is far from problem-free.  In particular, it requires that you don't try to operate on cells in a row other than the last one you loaded - it will deliberately panic if you do so.  

A *proper* fix to large sheet support basically requires a bottom-up rewrite of this library.  As other XLSX libraries are available for Go, and I personally haven't needed an XLSX library for Go in more than a decade, I don't think I'm likely to do that anytime soon ;-)

**Comment by QvodSoldier** [comment]
Hi, I found the the s="50" part of them is referring to the 50th element in the styles table. S stands for style and V stands for value?
![image](https://user-images.githubusercontent.com/35135086/116644958-4eb43e80-a9a7-11eb-827f-4f9c509b81c2.png)


So is it true that cells ​​like this actually not NULL.
```
<c r="A4" s="17" t="s">
    <v>15</v>
</c>
```
cells like this is actually NULL, they only have a style attributes.
```
<c r="H68" s="50"/>
<c r="I68" s="50"/>
```

I agree with the statement that the library just decode the xlsx file, It should not care about the meaning of the original data, event these data meaningless. 

But for some functions such as `xlsx.FileToSlice`, they only focus the data and don’t care about styles or other things. can we add a option just like ```withoutNULLValue```, when we call the function with the option, we simplify this sheets.xml(for example, delete those rows where they are NULL) before decode. 

If you agree with this solution, I would like to submit a pr.

**Comment by tealeg** [comment]
Oh, you're right! Sorry been a while since I looked.  Perhaps a "ValueOnly" flag? Then we could opt out of loading styles at all and save time and memory on every cell.

**Comment by QvodSoldier** [comment]
Hi, When I finished writing this part of the code, I suddenly realized that `VauleOnly` is not a common scenario.

It is very effective in dealing with this kind of file. NULL is meaningless in this file. But if B3 is not "pear", it is NULL, then that could means "Bob doesn't have any fruit he likes" or something else. 
![image](https://user-images.githubusercontent.com/35135086/117524644-c2ca9400-aff0-11eb-87cc-c18832bbfeba.png)

I try to figure out if NULL makes sense in the file, But I couldn't think of any good way to do it. 

So `ValueOnly` is a strict option, it treats all NULL values as meaningless, and it will remove all NULL value cells before decode worksheet.xml. Even though he could cause a misfire. Although this option can't solve the common scenario But Maybe this statement makes sense and it's can deal this issue, So i submitted this PR anyway [pr](https://github.com/tealeg/xlsx/pull/701) 😂😂
