### ISSUE TITLE
OpenFile hangs while reading a StarCalc spreadsheet

### ISSUE THREAD

**Issue by rbucker** [tealeg/xlsx#728]
I recognize this is a longshot. I do not even know how to generate one of these files... but a friend asked me to convert one to CSV from XLSX but it used all RAM and all SWAP.... I would share the file if I could but I cannot. So let this be a placeholder for someone who might.

THANKS

**Comment by tealeg** [comment]
@rbucker high memory usage is a fairly common complaint, there is essentially one course of action you can try: pass `xlsx.UseDiskVCellStore` as the final parameter to `OpenFIle`.

Beyond that, the issue is fairly fundamental to the design of this library and is one of the key reasons it is no longer actively maintained.
