### ISSUE TITLE
add "excel"

### ISSUE THREAD

**Issue by 89z** [tealeg/xlsx#749]
I think `excel` should be added to the description and/or topics. If you search this:

~~~
excel language:go
~~~

currently you will not find this repo.

**Comment by tealeg** [comment]
@89z this is an old project that is not actively maintained - making more people find it and use it is not a goal.

**Comment by 89z** [comment]
Can you please move ownership to me? I have Go experience, I can maintain the project.

**Comment by tealeg** [comment]
@89z well, it's not that easy. 

The first question is "why?" - why would you want to maintain this project?  There are other libraries that do what this library does and do it better.   This project was originally designed to read XLSX files - in adding the ability to write them it started to hit performance problems (especially around memory consumption), simply because it wasn't architected with those needs in mind.   This is definitely fixable, but it's a huge piece of work to take on.   Some attempts have been made to "hack" this problem, and there's probably some value left in profiling and fixing parts of the code (there are existing open issues that point to some leaks).   However, before taking that on, I'd stop and consider that since the heyday of this code, other libraries have come into existence.  So why bother to invest time to improve this one? 

The second question is one of trust.  There are two ways you could have control of this library:   

1. you could just fork this repo and maintain a new one in your name. 
2. you can convince me that I should give you control of this repo.

Option 1 you can do freely.  The project's license allows you to do that.  

Option 2 is a better deal for the Go community, as the project name stays the same.  However, you are not the first person to offer to do that.  I've had two other people maintain the project in the past.  I have no complaints about those people, but they eventually stopped doing it (which I completely understand).   The problem is that the project is in my name, and my namespace, and if it is in a bad condition then that reflects badly on me, even if I am not the current maintainer.   So before I'll hand over the keys to anyone, I would to know who they are, and why I should trust them with my name.  I hope that makes sense?

**Comment by 89z** [comment]
> I'd stop and consider that since the heyday of this code, other libraries have come into existence.

Perhaps you can name those libraries, and it would resolve this issue.

**Comment by tealeg** [comment]
@89z well, there's [excelize]( https://github.com/qax-os/excelize) which is linked from the README of this project.   I hope I didn't offend you with my response above - it wasn't intended to be unfriendly, I've just been down this road before.
