### ISSUE TITLE
不支持 go1.21 版本，麻烦给处理一下，谢谢

### ISSUE THREAD

**Issue by Yancy0220** [tealeg/xlsx#772]

**Comment by tealeg** [comment]
Translation: "The go 1.21 version is not supported. Please fix it, thank you."

**Comment by StevenMaude** [comment]
@tealeg: It *might* not need fixing here.

A project I maintain uses an older (v2) version of xlsx, and I found that spreadsheet cells were just empty with Go 1.21.0, similar to qax-os/excelize#1603. Upgrading to the latest v3 xlsx, I think, did seem to fix it, although I've not done much testing.

Otherwise, the incompatibility might be [this issue in Go](https://github.com/golang/go/issues/61881), which was reported by the lead developer of excelize. The fix should be in [Go 1.21.1](https://github.com/golang/go/issues/62051), which is [due in a few days (2023-09-06)](https://groups.google.com/g/golang-announce/c/UXJQvKffcao). So maybe worth retrying with Go 1.21.1 when it is released.

**Comment by khaledDiZ** [comment]
Thanks @StevenMaude I can confirm Upgrading to the latest v3 xlsx fixed the issue for me.

**Comment by StevenMaude** [comment]
Now that Go 1.21.1 is released, I went back to check the v2 behaviour with Go 1.21.1; it works as before too.

So I'd suggest that the fixes are either (or both) of:

* upgrade to xlsx v3
* for Go 1.21, use Go 1.21.1 or later

There's probably no more to do here, unless @Yancy0220 can describe a problem that is present even with xlsx v3 *and* Go 1.21.1 or later.

**Comment by Yancy0220** [comment]
感谢

| |
yangkexian0220
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Steven ***@***.***> |
| 发送日期 | 2023年09月11日 19:02 |
| 收件人 | tealeg/xlsx ***@***.***> |
| 抄送人 | Yancy ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [tealeg/xlsx] 不支持 go1.21 版本，麻烦给处理一下，谢谢 (Issue #772) |

Now that Go 1.21.1 is released, I went back to check the v2 behaviour with Go 1.21.1; it works as before too.

So I'd suggest that the fixes are either (or both) of:

upgrade to xlsx v3
for Go 1.21, use Go 1.21.1 or later

There's probably no more to do here, unless @Yancy0220 can describe a problem that is present even with xlsx v3 and Go 1.21.1 or later.

**Comment by tealeg** [comment]
Excellent, thank you @StevenMaude and @Yancy0220 !
